# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-05 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.AlterField(
            model_name='faresearch',
            name='averagePrice',
            field=models.FloatField(default=0),
        ),
    ]
