# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190206_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='AveragePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LowestPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='faresearch',
            name='averagePrice',
        ),
        migrations.RemoveField(
            model_name='faresearch',
            name='lowestPrice',
        ),
        migrations.AddField(
            model_name='lowestprice',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lowestPrices', to='main.FareSearch'),
        ),
        migrations.AddField(
            model_name='averageprice',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='averagePrices', to='main.FareSearch'),
        ),
    ]
