# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190207_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='faresearch',
            name='lowestPrice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
