# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_faresearch_lowestprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departTime', models.TimeField()),
                ('arriveTime', models.TimeField()),
                ('duration', models.DurationField()),
                ('businessFare', models.FloatField(default=-1)),
                ('anytimeFare', models.FloatField(default=-1)),
                ('wannaGetAwayFare', models.FloatField(default=-1)),
                ('numStops', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originAirport', models.CharField(max_length=5)),
                ('destinationAirport', models.CharField(max_length=5)),
                ('tripDate', models.DateTimeField()),
                ('numFlights', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='main.Trip'),
        ),
    ]
