# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190212_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arriveTime',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departTime',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.DurationField(default=None),
        ),
        migrations.AlterField(
            model_name='flight',
            name='numStops',
            field=models.IntegerField(default=None),
        ),
    ]
