# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190212_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='anytimeFare',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arriveTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='businessFare',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='numStops',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='wannaGetAwayFare',
            field=models.FloatField(),
        ),
    ]
