# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190212_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arriveTime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departTime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.CharField(max_length=50),
        ),
    ]
